CREATE TABLE AIRLINES(
	AIRLINE_CODE VARCHAR(10) NOT NULL,
    AIRLINE_NAME VARCHAR(40),
    PRIMARY KEY (AIRLINE_CODE));
INSERT INTO airlines VALUES ('AA','AMERICAN AIRLINES');
INSERT INTO airlines VALUES ('PIA','PAKISTAN INTERNATIONAL AIRLINE');
INSERT INTO airlines VALUES ('EA','EMIRATES AIRLINE');
INSERT INTO airlines VALUES ('QA','QATAR AIRLINE');
INSERT INTO airlines VALUES ('TA','TURKISH AIRLINE');
INSERT INTO airlines VALUES ('IA','ITEHAD AIRLINE');
INSERT INTO airlines VALUES ('UA','UNITED AIRLINE');
