CREATE TABLE AIRPORT(
	AIRPORT_CODE VARCHAR(10) NOT NULL,
    AIRPORT_NAME VARCHAR(50),
    CITY VARCHAR(30),
    COUNTRY VARCHAR(20),
    PRIMARY KEY (AIRPORT_CODE));
INSERT INTO airport VALUES('JIA','JINNAH INTERNATIONAL AIRPORT','KARACHI','PAKISTAN');
INSERT INTO airport VALUES('SIA','SHARJAH INTERNATIONAL AIRPORT','SHARJAH','UNITED ARAB EMIRATES');
INSERT INTO airport VALUES('AI','ANTALYA INTERNATIONAL','ANTALYA','TURKEY');
INSERT INTO airport VALUES('IHA','ISTANBUL HEZARFEN AIRFIELD','ISTANBUL','TURKEY');
INSERT INTO airport VALUES('AII','ALLAMA IQBAL INTERNATIONAL','LAHORE','PAKISTAN');
INSERT INTO airport VALUES('II','ISLAMABAD INTERNATIONAL','ISLAMABAD','PAKISTAN');
INSERT INTO airport VALUES('ADI','ABU DHABI INTERNATIONAL','ABU DHABI','UNITED ARAB EMIRATED');
INSERT INTO airport VALUES ('DI','DUBAI INTERNATIONAL','DUBAI','UNITED ARAB EMIRATES');
INSERT INTO airport VALUES('CM','CITY MANCHESTER','MANCHESTER','UNITED KINGDOM');
INSERT INTO airport VALUES('GI','GLASGOW INTERNATIONAL','GLASGOW','UNITED KINGDON');
INSERT INTO airport VALUES('LH','LONDON HEATHROW','LONDON','UNITED KINGDOM');
INSERT INTO airport VALUES('LIA','LOS ANGELES INTERNATIONAL AIRPORT','LOS ANGELES','U.S.A');
INSERT INTO airport VALUES('JFK','JOHN F. KENNEDY INTERNATIONAL AIRPORT','NEW YORK CITY','U.S.A');
INSERT INTO airport VALUES('TPI','TORONTO PEARSON INTERNATIONAL AIRPORT','TORONTO','CANADA');
