CREATE TABLE AIRPLANE(
	REG_NO VARCHAR(20) NOT NULL,
    PLANE_TYPE VARCHAR(30),
    AIRLINE_CODE VARCHAR(10) NOT NULL,
    AIRPORT_CODE VARCHAR(10),
    SEATS int,
    PRIMARY KEY (REG_NO),
    FOREIGN KEY (AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE),
    FOREIGN KEY (AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE));

INSERT INTO airplane VALUES('YA-AAA','INTERNATIONAL','EA','JFK',50);
INSERT INTO airplane VALUES('YY-ZZZ','INTERNATIONAL','QA','SIA',80);
INSERT INTO airplane VALUES('AA-TTT','INTERNATIONAL','TA','IHA',70);
INSERT INTO airplane VALUES('JJ-PPP','INTERNATIONAL','PIA','JIA',60);
INSERT INTO airplane VALUES('LL-PPP','NATIONAL','PIA','AII',90);
INSERT INTO airplane VALUES('GG-UUU','INTERNATIONAL','IA','GI',65);
INSERT INTO airplane VALUES('CC-AAA','INTERNATIONAL','UA','LIA',73);
