CREATE TABLE FARE(
	FARE_TYPE VARCHAR(10),
    PAYMENT INT,
    ROUTE_NO INT,
    CONSTRAINT PK_FARE PRIMARY KEY (FARE_TYPE,PAYMENT),
    FOREIGN KEY(ROUTE_NO) REFERENCES ROUTE(ROUTE_NO));

INSERT INTO FARE VALUES ('BUSINESS',100000,5);
INSERT INTO FARE VALUES ('ECONOMY', 50000, 5);
INSERT INTO FARE VALUES ('ECONOMY', 60000, 9);
INSERT INTO FARE VALUES ('BUSINESS',200000, 9);
INSERT INTO FARE VALUES ('BUSINESS', 60000, 2);
INSERT INTO FARE VALUES ('ECONOMY', 20000,2);
INSERT INTO fare VALUES('BUSINESS',400000,1);