CREATE TABLE AIRPORT(
	AIRPORT_CODE VARCHAR(10) NOT NULL,
    AIRPORT_NAME VARCHAR(50),
    CITY VARCHAR(30),
    COUNTRY VARCHAR(20),
    PRIMARY KEY (AIRPORT_CODE));
CREATE TABLE AIRLINES(
	AIRLINE_CODE VARCHAR(10) NOT NULL,
    AIRLINE_NAME VARCHAR(40),
    PRIMARY KEY (AIRLINE_CODE));
CREATE TABLE AIRPLANE(
	REG_NO VARCHAR(20) NOT NULL,
    PLANE_TYPE VARCHAR(10),
    AIRLINE_CODE VARCHAR(10) NOT NULL,
    AIRPORT_CODE VARCHAR(10),
    SEATS int,
    PRIMARY KEY (REG_NO),
    FOREIGN KEY (AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE),
    FOREIGN KEY (AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE));
CREATE TABLE FARE(
	FARE_TYPE VARCHAR(10),
    PAYMENT INT,
    CONSTRAINT PK_FARE PRIMARY KEY (FARE_TYPE,PAYMENT));
CREATE TABLE ROUTE(
	ROUTE_NO INT AUTO_INCREMENT,
    ROUTE_TYPE VARCHAR(10),
    STAY_LOC VARCHAR(30),
    R_FROM VARCHAR(30),
    R_TO VARCHAR(30),
    PRIMARY KEY(ROUTE_NO),
    FOREIGN KEY (FARE_TYPE) REFERENCES FARE(FARE_TYPE));

CREATE TABLE FLIGHT_TIME(
	AIRLINE_CODE VARCHAR(10),
	DEPT_DATE DATE,
    DEPT_TIME VARCHAR(10),
    ARR_DATE DATE,
    ARR_TIME VARCHAR(10),
    FLIGHT_NO VARCHAR(10),
    ROUTE_NO INT,
    CONSTRAINT PK_FLIGHT PRIMARY KEY (FLIGHT_NO, DEPT_DATE),
    FOREIGN KEY(ROUTE_NO) REFERENCES ROUTE(ROUTE_NO),
    FOREIGN KEY (AIRLINE_CODE) references AIRLINES(AIRLINE_CODE));

CREATE TABLE PASSENGER(
	CNIC VARCHAR(40),
    USERNAME VARCHAR(50),
    FIRSTNAME VARCHAR(30),
    LASTNAME VARCHAR(30),
    `PASSWORD` VARCHAR(90),
    PHONENO VARCHAR(30),
    GENDER VARCHAR(10),
    ADDRESS VARCHAR(50),
    EMAIL VARCHAR(30),
    DOB VARCHAR(40),
    CITY VARCHAR(30),
    STATE VARCHAR(30),
    PRIMARY KEY (CNIC));

CREATE TABLE BOOKING(
	BOOKING_ID INT NOT NULL auto_increment,
    BOOKING_DATE DATE,
    FLIGHT_NO VARCHAR(10),
    CNIC INT,
    PRIMARY KEY (BOOKING_ID),
    FOREIGN KEY (CNIC) REFERENCES PASSENGER(CNIC),
    FOREIGN KEY(FLIGHT_NO) REFERENCES FLIGHT_TIME(FLIGHT_NO));
commit;