CREATE TABLE ROUTE(
	ROUTE_NO INT AUTO_INCREMENT,
    ROUTE_TYPE VARCHAR(10),
    STAY_LOC VARCHAR(30),
    R_FROM VARCHAR(30),
    R_TO VARCHAR(30),
    PRIMARY KEY(ROUTE_NO),
    FOREIGN KEY (FARE_TYPE) REFERENCES FARE(FARE_TYPE));

INSERT INTO ROUTE (ROUTE_TYPE, STAY_LOC, R_FROM, R_TO) VALUES ('CONNECTING','DUBAI','ISTANBUL','LOS ANGELES');
INSERT INTO ROUTE (ROUTE_TYPE, STAY_LOC, R_FROM, R_TO) VALUES ('COONECTING','ABU DHABI','KARACHI','GLASGOW');
INSERT INTO ROUTE (ROUTE_TYPE, R_FROM, R_TO) VALUES ('DIRECT', 'ISLAMABAD','KARACHI');
INSERT INTO ROUTE (ROUTE_TYPE, R_FROM, R_TO) VALUES ('DIRECT','LOS ANGELES','NEW YORK CITY');
INSERT INTO ROUTE (ROUTE_TYPE, R_FROM, R_TO) VALUES ('DIRECT','TORONTO','LONDON');
INSERT INTO ROUTE (ROUTE_TYPE, R_FROM, R_TO) VALUES ('DIRECT', 'DUBAI', 'SHARJAH');
INSERT INTO ROUTE (ROUTE_TYPE, STAY_LOC, R_FROM, R_TO) VALUES ('CONNECTING', 'SHARJAH','LONDON','ANTALYA');
INSERT INTO ROUTE (ROUTE_TYPE, R_FROM, R_TO) VALUES ('DIRECT', 'ISTANBUL', 'LAHORE');

